version: '3'
services:
  posts:
    build:
      dockerfile: posts/Dockerfile
      context: ./services
    volumes:
      - /usr/app/node_modules
      - ./services/posts:/usr/app
  comments:
    build:
      dockerfile: comments/Dockerfile
      context: ./services
    volumes:
      - /usr/app/node_modules
      - ./services/comments:/usr/app
  query:
    depends_on:
      - event-bus
    build:
      dockerfile: query/Dockerfile
      context: ./services
    volumes:
      - /usr/app/node_modules
      - ./services/query:/usr/app
  moderation:
    build:
      dockerfile: moderation/Dockerfile
      context: ./services
    volumes:
      - /usr/app/node_modules
      - ./services/moderation:/usr/app
  event-bus:
    build:
      dockerfile: event-bus/Dockerfile
      context: ./services
    volumes:
      - /usr/app/node_modules
      - ./services/event-bus:/usr/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    ports:
      - '3000:3000'