exports.POST_CREATED = 'PostCreated'
exports.COMMENT_CREATED = 'CommentCreated'
exports.COMMENT_UPDATED = 'CommentUpdated'
exports.PENDING = 'pending'
exports.APPROVED = 'approved'
exports.DENIED = 'denied'
