apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: blog.io
      http:
        paths:
          - path: /posts
            pathType: Exact
            backend:
              service:
                name: posts-cluster-ip-service
                port:
                  number: 4000
